name: BE CI
on:
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install Dependencies
        run: npm install
      - name: Make .env
        run: |
          touch ./.env
          echo "${{ secrets.BE_CI_ENV }}" > ./.env
      - name: Make Cors Config
        run: |
          cd src/config
          touch ./cors.secure.ts
          echo "${{ secrets.BE_CONFIG }}" > ./cors.secure.ts
        shell: sh
      - name: Run Tests
        run: npm test
