name: BE CD

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: sudo docker login -u "${{secrets.BE_DOCKER_USERNAME}}" -p "${{secrets.BE_DOCKER_PASSWORD}}"

      - name: Build and push Docker image
        run: |
          touch ./.env
          echo "${{ secrets.BE_ENV }}" > ./.env
          cd src/config
          touch ./cors.secure.ts
          echo "${{ secrets.BE_CONFIG }}" > ./cors.secure.ts
          cd ../../
          sudo docker build -t ${{secrets.BE_DOCKER_USERNAME}}/${{secrets.BE_DOCKER_REPO}}:${{secrets.DOCKER_DEV_TAG}} --platform linux/amd64 .
          sudo docker push ${{secrets.BE_DOCKER_USERNAME}}/${{secrets.BE_DOCKER_REPO}}:${{secrets.DOCKER_DEV_TAG}}

  deploy-with-runner:
    needs: build-and-push
    name: Deploy with runner
    runs-on: self-hosted

    steps:
      - name: Prune old Docker images
        run: sudo docker image prune -a -f
      - name: Pull Docker image
        run: sudo docker pull ${{secrets.BE_DOCKER_USERNAME}}/${{secrets.BE_DOCKER_REPO}}:${{secrets.DOCKER_DEV_TAG}}
      - name: Delete Old docker container
        run: sudo docker rm -f server || true
      - name: Run Docker Container
        run: docker run —memory=1g —memory-swap=2g —restart=unless-stopped -d -p 80:8080 --name server --network ndd-network ${{secrets.BE_DOCKER_USERNAME}}/${{secrets.BE_DOCKER_REPO}}:${{secrets.DOCKER_DEV_TAG}}
